<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
k-nearest neighbors algorithm on iris_flowers Data
</font>
</h1>

<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
LOAD DATA
</font>
</h2>

In [ ]:
import numpy as np
irises = np.load('irises.npy')
types = np.load('types.npy')
new_irises = np.load('new_irises.npy')
n, m = len(irises), len(new_irises)
new_irises

(120,)

<h2 style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Calculate distances
</font>
</h2>

In [ ]:
import numpy as np
def calc_two_loops(new_points, points):
    m, n = len(new_points),len(points)
    d = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            d[i,j]=sum(np.square(points[j]-new_points[i]))
    return d 

d2 = calc_two_loops(new_irises, irises)
print(d2)


[[2.000e-02 3.700e-01 2.600e-01 ... 1.875e+01 2.029e+01 2.189e+01]
 [2.200e-01 3.000e-02 1.000e-01 ... 1.781e+01 1.987e+01 2.183e+01]
 [7.800e-01 1.850e+00 1.860e+00 ... 1.983e+01 2.073e+01 2.257e+01]
 ...
 [2.301e+01 2.362e+01 2.527e+01 ... 9.200e-01 2.200e-01 6.200e-01]
 [2.638e+01 2.711e+01 2.866e+01 ... 1.650e+00 6.300e-01 3.900e-01]
 [1.714e+01 1.725e+01 1.848e+01 ... 4.300e-01 4.100e-01 5.900e-01]]


In [ ]:
import numpy as np
def calc_one_loop(new_points, points):
    m, n = len(new_points), len(points)
    d = np.zeros((m, n))
    for i in range(m):
        x = np.square(new_points[i]-points)
        d[i] = x.sum(axis=1)
    return d
d2 = calc_one_loop(new_irises, irises)
print(d2)


[[2.000e-02 3.700e-01 2.600e-01 ... 1.875e+01 2.029e+01 2.189e+01]
 [2.200e-01 3.000e-02 1.000e-01 ... 1.781e+01 1.987e+01 2.183e+01]
 [7.800e-01 1.850e+00 1.860e+00 ... 1.983e+01 2.073e+01 2.257e+01]
 ...
 [2.301e+01 2.362e+01 2.527e+01 ... 9.200e-01 2.200e-01 6.200e-01]
 [2.638e+01 2.711e+01 2.866e+01 ... 1.650e+00 6.300e-01 3.900e-01]
 [1.714e+01 1.725e+01 1.848e+01 ... 4.300e-01 4.100e-01 5.900e-01]]


In [ ]:
import numpy as np
def calc_no_loop(new_points, points):
    return np.sum(np.square(new_points[:, np.newaxis, :] - points[np.newaxis, :, :]), axis=2)

d2 = calc_no_loop(new_irises, irises)
print(d2)


[[2.000e-02 3.700e-01 2.600e-01 ... 1.875e+01 2.029e+01 2.189e+01]
 [2.200e-01 3.000e-02 1.000e-01 ... 1.781e+01 1.987e+01 2.183e+01]
 [7.800e-01 1.850e+00 1.860e+00 ... 1.983e+01 2.073e+01 2.257e+01]
 ...
 [2.301e+01 2.362e+01 2.527e+01 ... 9.200e-01 2.200e-01 6.200e-01]
 [2.638e+01 2.711e+01 2.866e+01 ... 1.650e+00 6.300e-01 3.900e-01]
 [1.714e+01 1.725e+01 1.848e+01 ... 4.300e-01 4.100e-01 5.900e-01]]


<p 
<font face="vazir" size=3>
All outputs are same   
</font>
</p>

In [ ]:
d2 = calc_two_loops(new_irises, irises)
d1 = calc_one_loop(new_irises, irises)
d = calc_no_loop(new_irises, irises)
if np.allclose(d2, d1, d, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')


Fine!


<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Find k-nearest neighbors
</font>
</h2>

In [ ]:
k = 10
k_nearest = np.zeros((m, k))
j = 0
for i in np.argpartition(d,k, axis = 1):
    k_nearest[j]=i[:10]
    j+=1
k_nearest

array([[  6.,  14.,   0.,  32.,  22.,  17.,  39.,  21.,  23.,  37.],
       [ 10.,   1.,  30.,  24.,  20.,   2.,  36.,   3.,   6.,  28.],
       [ 27.,  13.,   8.,  39.,   4.,  29.,  15.,  12.,  26.,  25.],
       [ 14.,  17.,   0.,  39.,  37.,  22.,   8.,  32.,  26.,  13.],
       [ 21.,  20.,  30.,   3.,   9.,  24.,   6.,  19.,  35.,   5.],
       [ 10.,   1.,   2.,   3.,  38.,   5.,  36.,  30.,  24.,   9.],
       [ 10.,   1.,  30.,  24.,  20.,   2.,  36.,   3.,   6.,  28.],
       [  0.,   6.,  22.,  23.,  21.,  14.,   9.,  32.,  17.,  39.],
       [ 39.,  35.,  17.,  22.,   4.,  21.,  37.,  19.,   8.,  16.],
       [ 28.,   6.,  23.,   0.,  14.,  21.,  30.,  32.,  22.,   9.],
       [ 47.,  73.,  69.,  61.,  52.,  51.,  41.,  60., 101.,  58.],
       [ 71.,  43.,  65.,  64.,  77.,  72.,  66.,  76.,  74.,  54.],
       [ 71.,  65.,  74.,  64.,  66.,  77.,  76.,  54.,  57.,  49.],
       [ 64.,  65.,  74.,  66.,  43.,  50.,  54.,  72.,  77.,  71.],
       [ 78.,  60.,  47.,  41.,  7

<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Find type of k-nearest neighbors
</font>
</h2>

In [ ]:
x = np.argpartition(d,k, axis = 1)
k_nearest_types = np.zeros((m, k))
for i in range(len(x)):
    a = x[i][:10]
    for j in range(len(a)):
        k_nearest_types[i][j] = types[a[j]]

<h2  style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Find type of flowers
</font>
</h2>

In [ ]:
from scipy import stats

In [ ]:
predicted_types = stats.mode(k_nearest_types, axis=1).mode.reshape(m)
# predicted_types = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
predicted_types

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [ ]:
new_types = np.load('new_types.npy')
s = 0
for i in range(m):
    if new_types[i]==predicted_types[i]:
        s+=1
accuracy = s/m
print('Accuracy:', accuracy)

Accuracy: 1.0
